### ISSUE TITLE
Consumer offset not working with setDurableName in the streaming connector

### ISSUE THREAD

**Issue by jainnidhi703** [Logimethods/nats-connector-spark#4]
While my producer is running, but the consumer is restarted, messages are lost in the interval of consumer restart. The option setDurableName is added, still, messages are lost in between.

**Comment by laugimethods** [comment]
@jainnidhi703 I'll investigate your issue while upgrading the connector...
Any more details to share? In particular, your source code?

Is it from NATS to Spark or from Spark to NATS?

Do you reproduce the same issue with the new connector 1.0.0-SNAPSHOT?

Best regards,
Laurent

**Comment by jainnidhi703** [comment]
Will share the details in a day or 2.

Thanks,
Nidhi Jain

**Comment by laugimethods** [comment]
@jainnidhi703, please try with the new version of the connector (1.0.0-SNAPSHOT), with both constant `Queue` & `DurableName` parameters setted (you have no control of the `ClientID` used by the multiple Spark jobs since they are generated so to be unique):
```
NatsToSparkConnector
 .../...
    .withNatsQueue(queue)
    .setDurableName(durableName)
.../...
```

See https://github.com/Logimethods/nats-connector-spark/tree/version_1.0.0

References:
- https://github.com/nats-io/java-nats-streaming#durable-subscriptions
- https://github.com/nats-io/nats-streaming-server#durable

**Comment by jainnidhi703** [comment]
It works. Thanks

**Comment by laugimethods** [comment]
@jainnidhi703 comment + dedicated JUnit test: https://github.com/Logimethods/nats-connector-spark/blob/version_1.0.0/src/test/java/com/logimethods/connector/nats/to_spark/api/NatsStreamingToSparkTest.java#L142
